apiVersion: apps/v1
kind: Deployment #StatefulSet?
metadata:
  name: {{ .Release.Name }}-{{ .Values.prysm.validator.name }}
  labels:
    release: {{ .Release.Name }}    
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.prysm.validator.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.prysm.validator.name }}
        release: {{ .Release.Name }}  
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: release
                operator: In
                values:
                - {{ .Release.Name }}
            topologyKey: kubernetes.io/hostname
      volumes:
      - name: {{ .Release.Name }}-chain-state
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-{{ .Values.storage.claim }}                    
      nodeSelector:
        eth2: "true"          
      containers:
        - name: {{ .Values.prysm.validator.name }}
          image: {{ .Values.prysm.validator.image.repository }}:{{ .Values.prysm.validator.image.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args:
          - "--accept-terms-of-use"
          - "--chain-config-file={{ .Values.shared.configDataDir }}/config.yaml"
          - "--beacon-rpc-provider={{ .Release.Name }}-{{ .Values.prysm.beacon.name }}-svc:{{ .Values.prysm.beacon.ports.node }}"
          - "--datadir=/consensus-data-val"
          - "--suggested-fee-recipient={{ .Values.prysm.shared.feeRecipent }}"
          - "--wallet-dir=/data/val_keys/prysm"          
          - "--wallet-password-file={{ .Values.shared.configDataDir }}/wallet_password.txt"
          - "--force-clear-db"
          resources:
            requests:
              memory: {{ .Values.prysm.validator.resources.requests.memory }}
              cpu: {{ .Values.prysm.validator.resources.requests.cpu }}
            limits:
              memory: {{ .Values.prysm.validator.resources.limits.memory }}
              cpu: {{ .Values.prysm.validator.resources.limits.cpu }}
          volumeMounts:               
            - name: {{ .Release.Name }}-chain-state
              mountPath: /data
      initContainers:
        - name: {{ .Release.Name }}-wait-for-besu
          image: {{ .Values.busybox.image.repository }}:{{ .Values.busybox.image.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }} 
          command:
            - "/bin/sh"
            - "-c"
            - >
              timeout 900 sh -c '
                start_time=$(date +%s)
                while ! nc -z -v {{ .Release.Name }}-{{ .Values.besu.name }}-svc {{ .Values.besu.ports.execution }}; do
                  current_time=$(date +%s)
                  elapsed_time=$((current_time - start_time))
                  remaining_time=$((900 - elapsed_time))
                  echo "Waiting for Besu (Remaining time: $remaining_time seconds)..."
                  sleep 2
                done'