apiVersion: v1
kind: Service
metadata:
  labels:
    app: terrad
    release: {{ .Release.Name }}
  name: terrad
spec:
  ports:
    - name: "26657"
      port: 26657
      targetPort: 26657
    - name: "1317"
      port: 1317
      targetPort: 1317
    - name: "9090"
      port: 9090
      targetPort: 9090
    - name: "9091"
      port: 9091
      targetPort: 9091
  selector:
    app: terrad
    release: {{ .Release.Name }}
