apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-chain-state-storage
  labels:
    release: {{ .Release.Name }}      
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
