version: 1
project_name: mockserver

env:
  - IMG_PRE={{ if index .Env "IMAGE_PREFIX"  }}{{ .Env.IMAGE_PREFIX }}{{ else }}localhost:5001{{ end }}
  - TAG={{ if index .Env "IMAGE_TAG" }}{{ .Env.IMAGE_TAG }}{{ else }}latest{{ end }}

# Build settings for binaries
builds:
  - id: mockserver
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - '-s -w' # Strip debug information to reduce binary size
    binary: 'mockserver_{{ .Os }}_{{ .Arch }}'

archives:
  - format: binary

dockers:
  - id: linux-amd64-mockserver
    goos: linux
    goarch: amd64
    image_templates:
      - '{{ .Env.IMG_PRE }}/mockserver:{{ .Tag }}'
      # - "{{ .Env.IMG_PRE }}/mockserver:latest"
      - '{{ .Env.IMG_PRE }}/mockserver:debug' # DEBUG: Using for testing
    dockerfile: Dockerfile
    build_flag_templates:
      - --platform=linux/amd64
      - --pull
      - --build-arg=TARGETARCH=amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
  - id: linux-arm64-mockserver
    goos: linux
    goarch: arm64
    image_templates:
      - '{{ .Env.IMG_PRE }}/mockserver:{{ .Tag }}-arm64'
      # - "{{ .Env.IMG_PRE }}/mockserver:latest-arm64"
      - '{{ .Env.IMG_PRE }}/mockserver:debug-arm64' # DEBUG: Using for testing
    dockerfile: Dockerfile
    build_flag_templates:
      - --platform=linux/arm64
      - --pull
      - --build-arg=TARGETARCH=arm64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
changelog:
  disable: 'true'
