apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-relay-{{ .Values.idx }}
  name: postgres-relay-{{ .Values.idx }}
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: postgres-relay-{{ .Values.idx }}
