name: Generate go-docs

on:
  pull_request:
    types:
      - labeled
      - reopened
      - synchronize

jobs:
  generate_docs_new_pr:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'generate_go_docs') }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read    

    steps:
      - name: Setup GitHub Token for reading Generate Go Doc Repo
        id: setup-github-token-read
        uses: smartcontractkit/.github/actions/setup-github-token@9e7cc0779934cae4a9028b8588c9adb64d8ce68c # setup-github-token@0.1.2
        with:
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN_READ_GENERATE_GO_DOC_REPO }}
          aws-lambda-url: ${{ secrets.GATI_LAMBDA_TT_URL }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Configure git for private repository and install go doc generator
        env:
          GOPRIVATE: github.com/smartcontractkit/generate-go-function-docs
        run: |
          git config --global \
          url."https://x-access-token:${{ steps.setup-github-token-read.outputs.access-token }}@github.com/".insteadOf "https://github.com/"
          go install github.com/smartcontractkit/generate-go-function-docs@latest

      - name: Install gopls
        shell: bash
        run: |
          go install golang.org/x/tools/gopls@latest             

      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0             

      - name: Setup Git to use GitHub Actions bot
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"          

      - name: Create a new branch
        run: |
          git checkout -b ${{ github.event.pull_request.head.ref }}-docs

      - name: Generate go docs
        shell: bash
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # Add go binary to PATH
          PATH=$PATH:$(go env GOPATH)/bin
          export PATH
          # TODO check why this flag is needed, if it has a default!
          generate-go-function-docs diff -b ${{ github.event.pull_request.base.sha }} -c ${{ github.event.pull_request.head.sha }} -g fake_slash -f .

      - name: Make sure code still compiles
        run: |
          go mod tidy
          go build ./...

      - name: Commit changes
        run: |
          git add .
          git commit -m "Add automatically generated go documentation"
          git push origin ${{ github.event.pull_request.head.ref }}-docs

      - name: Setup GitHub Token for creating a new PR
        id: setup-github-token-write
        uses: smartcontractkit/.github/actions/setup-github-token@9e7cc0779934cae4a9028b8588c9adb64d8ce68c # setup-github-token@0.1.2
        with:
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN_READ_GENERATE_GO_DOC_REPO }}
          aws-lambda-url: ${{ secrets.GATI_LAMBDA_TT_URL }}
          aws-region: ${{ secrets.AWS_REGION }}          

      - name: Create a new PR targeting current PR
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ github.event.pull_request.head.ref }}
          branch: ${{ github.event.pull_request.head.ref }}-docs
          title: "Go docs for PR#${{ github.event.pull_request.number }}"
          body: "This PR contains automatically generated go documentation for the PR#${{ github.event.pull_request.number }}. Please review the changes."
