name: Test Mockserver

on:
  push:
    branches:
      - main
    tags:
      - 'mockserver/v*.*.*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Check for changes in Mockserver
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            src:
              - 'mockserver/**'
      - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
        if: steps.changes.outputs.src == 'true'
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run tests
        if: steps.changes.outputs.src == 'true'
        run: |
          nix develop -c go test ./mockserver/...
